databases:
  - name: muse
    plan: free
    databaseName: muse
    user: muse

services:
  - type: web
    name: muse
    plan: free
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: muse
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
